version: '3.8'

services:
  catalog_postgresql_db:
    container_name: catalog-postgresql-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - catalog_postgresql_db:/var/lib/postgresql/data

  customer_postgresql_db:
    container_name: customer-postgresql-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5433"
    volumes:
      - customer_postgresql_db:/var/lib/postgresql/data

  postgresql_pgadmin:
    image: dpage/pgadmin4
    container_name: postgresql-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: 12345
    ports:
      - "8888:80"

volumes:
  catalog_postgresql_db:
  customer_postgresql_db: