version: '3.8'

services:
  postgresql:
    container_name: postgresql
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: catalog_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: catalog-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: strong-password
    ports:
      - "8888:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgresql_data:
  pgadmin_data: