server:
  port: 8082 # run on random port if set 0

spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:5434/order_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect